name: Build and deploy Diplodoc docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".yfm"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/docs.yml"

  pull_request:
    paths:
      - "docs/**"
      - ".yfm"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/docs.yml"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Diplodoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install project dependencies
        run: npm install

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build docs with Diplodoc
        uses: diplodoc-platform/docs-build-action@v3
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_URL: https://api.github.com
          VCS_CONNECTOR_TYPE: github
          VCS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          revision: ${{ github.event.pull_request.head.sha || github.sha }}
          src-root: "./docs"
          lint-root: "./docs-html"
          build-root: "./docs-md"

      - name: Disable Jekyll
        run: touch ./docs-html/.nojekyll

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs-html"

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4